// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaQSN5ehylYNRjn2GTVZYxWxpARMer7zA',
    appId: '1:420055386320:android:867e5b39db2860547176d5',
    messagingSenderId: '420055386320',
    projectId: 'mobile-app-development-78ac2',
    storageBucket: 'mobile-app-development-78ac2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX8I9Qbv2RZGB9QMkNlqFcRWEAPCG65LM',
    appId: '1:420055386320:ios:ca74f99eedfa8bd77176d5',
    messagingSenderId: '420055386320',
    projectId: 'mobile-app-development-78ac2',
    storageBucket: 'mobile-app-development-78ac2.firebasestorage.app',
    iosBundleId: 'inti.edu.mobileAppDevelopment',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX8I9Qbv2RZGB9QMkNlqFcRWEAPCG65LM',
    appId: '1:420055386320:ios:ca74f99eedfa8bd77176d5',
    messagingSenderId: '420055386320',
    projectId: 'mobile-app-development-78ac2',
    storageBucket: 'mobile-app-development-78ac2.firebasestorage.app',
    iosBundleId: 'inti.edu.mobileAppDevelopment',
  );

}